namespace TotallyHot.ArcRouter.Gui.Charts;

/// <summary>One turn's raw token counts, as input to <see cref="TokenCompoundingSeries"/>.</summary>
/// <param name="TurnNumber">The turn's 1-based position within its conversation.</param>
/// <param name="PromptTokens">Prompt tokens sent to the LLM for this turn.</param>
/// <param name="CompletionTokens">Completion tokens generated by the LLM for this turn.</param>
public readonly record struct TurnTokenPoint(int TurnNumber, int PromptTokens, int CompletionTokens);

/// <summary>One point on the cumulative token-compounding line chart.</summary>
/// <param name="TurnNumber">The turn this point represents.</param>
/// <param name="CumulativePromptTokens">Prompt tokens summed over this turn and all prior turns.</param>
/// <param name="CumulativeCompletionTokens">Completion tokens summed over this turn and all prior turns.</param>
public sealed record CompoundingPoint(int TurnNumber, int CumulativePromptTokens, int CumulativeCompletionTokens)
{
    /// <summary>Cumulative prompt + completion tokens at this turn.</summary>
    public int CumulativeTotalTokens => CumulativePromptTokens + CumulativeCompletionTokens;
}

/// <summary>
/// Builds the token-compounding ("hockey stick") series behind the Live Stream conversation summary's
/// sparkline (<see cref="BuildSparkline"/>); <see cref="Build"/> is the cumulative variant retained for
/// reuse. Pure and stateless: no dependency on the Gui project's Blazor/MAUI types, so it's
/// unit-testable without them. (The Cost Analytics token chart is now the <c>Tokens</c> metric of
/// <see cref="CostChartBuilder"/>.)
/// </summary>
public static class TokenCompoundingSeries
{
    /// <summary>
    /// Builds the cumulative prompt/completion token series across turns, ordered by turn number.
    /// </summary>
    /// <param name="turns">The conversation's turns, in any order.</param>
    /// <returns>One <see cref="CompoundingPoint"/> per turn, ordered by <see cref="TurnTokenPoint.TurnNumber"/>.</returns>
    public static IReadOnlyList<CompoundingPoint> Build(IReadOnlyList<TurnTokenPoint> turns)
    {
        ArgumentNullException.ThrowIfNull(turns);

        var points = new List<CompoundingPoint>(turns.Count);
        var cumulativePrompt = 0;
        var cumulativeCompletion = 0;

        foreach (var turn in turns.OrderBy(t => t.TurnNumber))
        {
            cumulativePrompt += turn.PromptTokens;
            cumulativeCompletion += turn.CompletionTokens;
            points.Add(new CompoundingPoint(turn.TurnNumber, cumulativePrompt, cumulativeCompletion));
        }

        return points;
    }

    /// <summary>
    /// Builds a compact per-turn (non-cumulative) total-token series, ordered by turn number, sized
    /// for a small sparkline rather than a full axis-labeled chart.
    /// </summary>
    /// <param name="turns">The conversation's turns, in any order.</param>
    /// <returns>One total-token value per turn, ordered by <see cref="TurnTokenPoint.TurnNumber"/>.</returns>
    public static IReadOnlyList<int> BuildSparkline(IReadOnlyList<TurnTokenPoint> turns)
    {
        ArgumentNullException.ThrowIfNull(turns);

        return turns
            .OrderBy(t => t.TurnNumber)
            .Select(t => t.PromptTokens + t.CompletionTokens)
            .ToList();
    }
}

