namespace TotallyHot.ArcRouter.Gui.Charts;

/// <summary>One turn's raw token counts, as input to <see cref="TokenCompoundingSeries"/>.</summary>
/// <param name="TurnNumber">The turn's 1-based position within its conversation.</param>
/// <param name="PromptTokens">Prompt tokens sent to the LLM for this turn.</param>
/// <param name="CompletionTokens">Completion tokens generated by the LLM for this turn.</param>
public readonly record struct TurnTokenPoint(int TurnNumber, int PromptTokens, int CompletionTokens);

/// <summary>
/// Builds the compact per-turn token series behind the Live Stream conversation summary's sparkline.
/// Pure and stateless: no dependency on the Gui project's Blazor types, so it's unit-testable without
/// them. (The Cost Analytics token chart is the <c>Tokens</c> metric of <see cref="CostChartBuilder"/>.)
/// </summary>
public static class TokenCompoundingSeries
{
    /// <summary>
    /// Builds a compact per-turn (non-cumulative) total-token series, ordered by turn number, sized
    /// for a small sparkline rather than a full axis-labeled chart.
    /// </summary>
    /// <param name="turns">The conversation's turns, in any order.</param>
    /// <returns>One total-token value per turn, ordered by <see cref="TurnTokenPoint.TurnNumber"/>.</returns>
    public static IReadOnlyList<int> BuildSparkline(IReadOnlyList<TurnTokenPoint> turns)
    {
        ArgumentNullException.ThrowIfNull(turns);

        return [.. turns
            .OrderBy(t => t.TurnNumber)
            .Select(t => t.PromptTokens + t.CompletionTokens)];
    }
}
